<div id="login-container">
    <div id="login-header"><img src="<? echo BASE_URL . 'core/views/images/admin.jpg'; ?>" width="64" height="64"/></div>
    <div id="login-contents">
        <form id="login-form" method="post" action="../core/controllers/admin_login.php">
            <div id="username-container">
                <label for="ba_username">Username</label><br/>
                <input id="ba_username" type="text" name="ba_username" />
            </div>
            <div id="password-container">
                <label for="ba_password">Password</label><br/>
                <input id="ba_password" type="password" name="ba_password" />
            </div>
            <div id="login-button-container">
                <button id="ba_login_button" type="submit">Login</button>
            </div>
        </form>
        <div>
            <span><a href="#">Forgot Password?</a></span>
        </div>
    </div>
</div>