<div>
    <div>Complete the information below to install your site.</div><br/>
    <form id="ba-installer-form" method="post" action="installer.php">
        <label>Site Title</label><br/>
        <input type="text" name="site-title"/><br/>
        <label>Base URL</label><br/>
        <input type="text" name="base-url"/><br/>
        <label>Admin Folder</label><br/>
        <input type="text" name="admin-folder"/><br/>
        <label>Themes Folder</label><br/>
        <input type="text" name="themes-folder"/><br/>
        <label>Database Driver</label><br/>
        <input type="text" name="database-driver" placeholder="mysql"/><br/>
        <label>Database Host</label><br/>
        <input type="text" name="database-host" placeholder="localhost"/><br/>
        <label>Database Name</label><br/>
        <input type="text" name="database-name"/><br/>
        <label>Database User</label><br/>
        <input type="text" name="database-user"/><br/>
        <label>Database Password</label><br/>
        <input type="password" name="database-password"/><br/>
        <label>Verify Password</label><br/>
        <input type="password" name="verify-password"/><br/>
        <label>Database Table Prefix</label><br/>
        <input type="text" name="table-prefix"/><br/><br/>
        <button type="submit">Install</button>
    </form>
</div>